# Limits (0 or negativ = no limits)
# These are default limits. For a more granular control see permissions
limits:
  max-claims-per-player: 150
  max-chunks-per-player: 1000
  max-claim-name-length: 32 #max 250
  max-lore-length: 1024
  max-chunk-loaders: 10 #How much chunks a player can perma load

chunkloader: true # set this to false if you dont want to use the chunkloader

show-claim-duration-seconds: 60 # How long the claim border is shown when using /showclaim

# How big the border of a claimed chunk should be displayed on the map
marker:
  stroke-weight: 2

color:
  names:
    red: "§cRot"
    blue: "§9Blau"
    green: "§aGrün"
    yellow: "§eGelb"
    purple: "§5Lila"
    orange: "§6Orange"
    white: "§fWeiß"
    black: "§0Schwarz"
    gray: "§7Grau"
    pink: "§dPink"
    cyan: "§bCyan"
    lime: "§aLime"
    light_blue: "§3Hellblau"
    magenta: "§dMagenta"
    brown: "§6Braun"
    gold: "§6Gold"
    turquoise: "§bTürkis"
  values:
    red: "#FF0000"
    blue: "#0000FF"
    green: "#00FF00"
    yellow: "#FFFF00"
    purple: "#800080"
    orange: "#FFA500"
    white: "#FFFFFF"
    black: "#000000"
    gray: "#808080"
    pink: "#FFC0CB"
    cyan: "#00FFFF"
    lime: "#00FFAA"
    light_blue: "#ADD8E6"
    magenta: "#FF00FF"
    brown: "#A52A2A"
    gold: "#FFD700"
    turquoise: "#40E0D0"
  transparency:
    stroke: 0.3
    fill: 0.6

# Color/Styling for BossBar. For Options see: https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Bossbar#color
ClaimBossBar:
  color: "GREEN"
  style: "SEGMENTED_6"
ChunkLoaderBossBar:
  color: "YELLOW"
  style: "PROGRESS"


# Messages shown to players. The placeholders in <> will be replaced with dynamic values. They can be obmitted but extra placeholders will not be recognized.
# The Plugin uses some internal placeholders that get replaced with dynamic values:
# %chunk_x% - Chunk X Coordinate
# %chunk_z% - Chunk Z Coordinate
# %claim_name% - Claim Name
# %claim_new_name% - New Claim Name
# %max_chunks% - max chunks per player
# %max_claims% - max claims per player
# %max_length% - max claim name length
# %owner% - Owner of the claim
# %player% - Player name
# %chunk_count% - Number of chunks claimed by the player
# %claim_count% - Number of claims created by the player
# %deleteclaim_confirm% - trigger word to confirm claim deletion
# %renameclaim_confirm% - trigger word to confirm claim renaming/merging

messages:
  #command usage
  usage:
    claim: "§aNutze §e/claim \"claim-name\"§a um den Chunk in dem du stehst zu claimen. Der Name wird anderen Spielern und auf der Karte angezeigt. Lässt du den Namen weg, wird der chunk zu deinem zuletzt bearbeiteten Claim hinzugefügt."
    autoclaim: "§aNutze §e/autoclaim \"claim-name\"§a um automatisch die chunks zu claimen in denen du dich befindest. Mit §e/autoclaim off§a schaltest du es wieder aus. Um AutoClaim zu nutzen, musst du zuerst einen Claim mit §e/claim \"claim-name\"§a erstellen."
    claiminfo: "§aNutze §e/claiminfo§a um Informationen über den Chunk in dem du stehst zu erhalten."
    listclaims: "§aNutze §e/listclaims§a um eine Liste deiner Claims anzuzeigen."
    renameclaim: "§aNutze §e/renameclaim \"alter-name\" \"neuer-name\"§a um einen Claim umzubenennen."
    renameclaim-other: "§aNutze §e/renameclaim -p <Spieler> \"alter-name\" \"neuer-name\"§a um einen Claim eines anderen Spielers umzubenennen."
    deleteclaim: "§aNutze §e/deleteclaim \"name\"§a um einen Claim mit allen seinen Chunks zu löschen."
    unclaim: "§aMit §e/unclaim§a löscht du nur den Chunk in dem du stehst aus einen Claim. Nutze §e/deleteclaim \"<name>\"§a, um den gesamten Claim zu löschen."
    claimcolor: "§aMit §e/claimcolor \"claim-name\" <farbe>§a änderst du die Farbe der Markierung für deine Claims auf der Karte."
    showclaim: "§aMit §e/showclaim \"claim-name\"§a werden die Grenzen des Claims für eine bestimmte Zeit angezeigt."
    chunkloader: "§aMit §e/chunkloader add <name>§a lädst du den Chunk in dem du stehst permanent. Mit §e/chunkloader remove <name>§a entfernst du den Chunk-Loader wieder. Mit §e/chunkloader list§a siehst du eine Liste deiner Chunk-Loader."
    claimlore: "§aMit §e/claimlore set \"claim-name\" <beschreibung>§a kannst du eine Beschreibung für deinen Claim festlegen. Mit §e/claimlore get \"claim-name\"§a kannst du die aktuelle Beschreibung anzeigen lassen."
  # command results
  claim:
    success: "§aChunk %chunk_x%,%chunk_z% wurde für %player% geclaimt. Er gehört nun zum/zur %claim_name%"
    addedToClaim: "§aChunk %chunk_x%,%chunk_z% wurde für %player% geclaim und zum/zur %claim_name% hinzugefügt."
    claimed-already: "§aDieser Chunk ist bereits von dir geclaimt. Nutze §e/unclaim§a um ihn freizugeben."
    claimed-by-other: "§aDieser Chunk ist bereits von jemand anderen geclaimt."
    claim-belongs-to-other: "§aDer Claim %claim_name% gehört einen anderen Spieler."
    could-not-create-claim: "§cDer Claim %claim_name% konnte hier nicht erstellt werden."
    can-not-be-claimed: "§cDer Chunk kann nicht geclaimt werden."
    max-claims-reached: "§aDu hast die maximale Anzahl an Claims erreicht. Du kannst maximal %max_claims% Claims erstellen."
    max-chunks-reached: "§aDu hast die maximale Anzahl an geclaimten Chunks erreicht. Du kannst maximal %max_chunks% Chunks claimen."
    name-too-long: "§aDer Claim-Name darf maximal %max_length% Zeichen lang sein."
    claim-name-not-allowed: "§aDiesen Claimnamen darfst du leider nicht verwenden."
  autoclaim:
    enabled: "§aAutoClaim für Claim %claim_name% aktiviert."
    disabled: "§aAutoClaim deaktiviert."
    no-target-claim-set: "§aDer Claim existiert nicht. Nutze zuerst §e/claim \"%claim_name%\"§a um ihn zu erstellen und diesen ersten Chunk zu claimen."
    chunk-belongs-to-different-claim: "§aDer Chunk %chunk_x%,%chunk_z% gehört zu einem anderen Claim und wurde nicht erneut geclaimt. Nutze §e/unclaim§a um ihn freizugeben."
  unclaim:
    success: "§aChunk %chunk_x%,%chunk_z% aus Claim %claim_name% entfernt."
    none: "§aHier ist kein Claim gesetzt."
    other-owner: "§aDieser Chunk gehört %owner%. Du kannst nur deine eigenen Chunks unclaimen."
    usage: "§aMit /unclaim löscht du nur den Chunk in dem du stehst aus einen Claim. Nutze §e/deleteclaim \"%claim_name%\"§a, um den gesamten Claim zu löschen."
  claiminfo:
    free: "§aDieser Chunk ist frei und gehört niemandem."
    claimed: "§aDieser Chunk gehört %owner% im Claim %claim_name%."
  no-claims: "§aDu hast noch keine Claims gesetzt. Nutze /claim um einen Chunk zu claimen."
  list-claims:
    header: "§aDeine Claims:"
    header-other: "§aClaims von %player%:"
    entry: "§6- %claim_name%: %chunk_count% Chunks"
    summary: "§aInsgesamt hast du %chunk_count% von %max_chunks% Chunks geclaimt und %claim_count% von %max_claims% möglichen Claims erstellt. "
    summary-other: "§aInsgesamt hat %player% %chunk_count% von %max_chunks% Chunks geclaimt und %claim_count% von %max_claims% möglichen Claims erstellt. "
    no-claims-other: "§aSpieler %player% hat keine Claims."
  deleteclaim:
    success: "§aDer Claim %claim_name% wurde gelöscht und alle Chunks wurden freigegeben."
    not-owner: "§aDu besitzt keinen Claim mit dem Namen %claim_name%."
    confirm: "§aBist du sicher, dass du den Claim %claim_name% und alle seine Chunks löschen möchtest? Nutze §e/deleteclaim %claim_name% %deleteclaim_confirm% §aum den Löschvorgang abzuschließen."
    none: "§aDu hast keine Claims zum Löschen."
  renameclaim:
    success: "§aDer Claim %claim_name% wurde in %claim_new_name% umbenannt."
    merge-confirm: "§aBist du sicher, dass du den Claim %claim_name% mit %claim_new_name% zusammenführen möchtest? Nutze §e/rename %claim_name% %claim_new_name% %renameclaim_confirm% §aum den Vorgang durchzuführen."
    none: "§aKeine Claims zum Umbenennen verfügbar."
    merge-success: "§aDer Claim %claim_name% wurde mit %claim_new_name% zusammengeführt."
  claimlore:
    get: "§aDer Claim %claim_name% hat folgende Beschreibung: &e<hover:show_text:'Klick auf den Text um die Beschreibung zu kopieren.'><click:copy_to_clipboard:%claim_lore%>\"%claim_lore%\"</click>"
    set: "§aDie Beschreibung für den Claim %claim_name% wurde überschrieben."
    too-long: "§aDie Beschreibung darf maximal %max_length% Zeichen lang sein."
    invalid-characters: "§aDie Beschreibung enthält ungültige Zeichen."
  claimcolor:
    set: "§aDie Farbe für den Claim %claim_name% wurde auf %color_name% gesetzt."
    invalid-color: "§aDie angegebene Farbe ist ungültig."
  chunkloader:
    enabled: "§aDieser Chunk (%chunkloader_name%) wird nun permanent geladen. Du hast nun %current_chunk_loaders% von %max_chunk_loaders% Chunk-Loadern verwendet."
    max-reached: "§aDu hast die maximale Anzahl an Chunk-Loadern erreicht. Du kannst maximal %max_chunk_loaders% Chunks permanent laden. Entferne zuerst einen bestehenden Chunk-Loader mit §e/chunkloader remove§a."
    already-enabled: "§aDieser Chunk wird bereits unter den Namen %chunkloader_name% permanent geladen."
    disabled: "§aDer Chunkloader %chunkloader_name% wurde entfernt und sein Chunk wird nicht mehr permanent geladen. Du hast nun %current_chunk_loaders% von %max_chunk_loaders% Chunk-Loadern verwendet."
    already-enabled-other: "§aDieser Chunk wird von %owner% permanent geladen."
    can-not-be-loaded: "§cDieser Chunk kann nicht permanent geladen werden."
    name-invalid: "§aDer angegebene Name ist ungültig."
    not-found: "§aEs wurde kein Chunk-Loader mit diesen Namen gefunden."
  chunkloaderlist:
    header: "§aDeine Chunk-Loader: (%current_chunk_loaders% von %max_chunk_loaders% möglichen)"
    header-other: "§Chunk-Loader von %owner%:"
    entry: "§6- %chunkloader_name% in Welt: %world%, Koordinaten: %x%, %y%, %z%"
    no-chunkloaders: "§aDu hast keine Chunk-Loader gesetzt."
    no-chunkloaders-other: "§aSpieler %owner% hat keine Chunk-Loader gesetzt."
  unknown-error: "§cEin unbekannter Fehler ist aufgetreten. Bitte kontaktiere einen Administrator."
  missing-permission: "§cDu hast nicht genug Berechtigungen um diesen Befehl auszuführen."
  player-not-found: "§cDer Spieler %player_name% wurde nicht gefunden."
  claim-not-found: "§cEinen Claim mit dem Namen %claim_name% wurde nicht gefunden."
  not-implemented: "§cOh je! Diese Funktion ist noch nicht implementiert."
  showclaim:
    shown: "§aDie Grenzen des Claims %claim_name% werden für %show-claim-duration-seconds% Sekunden angezeigt."
  Pl3xMap:
    layer-name: "Claims"
    hover-text:
      named-claim: "%claim_name% von %owner%"
  ClaimBossBar:
    # Do not use colors here, as it will be overridden by the color of the claim
    title: "Claim: %claim_name% | Besitzer: %owner%"
  ChunkLoaderBossBar:
    title: "<yellow>ChunkLoader: %chunkloader_name% aktiv."




# These are words that need to be typed to confirm/trigger certain actions
# They can not be used in other contexts (e.g. as claim names)
# Note: They are not case-sensitive. If you change them the plugin makes sure that no conflicts arise. It will rename existing claims if necessary.

trigger-words:
    deleteclaim-confirm: "confirm"
    renameclaim-confirm: "confirm"
    autoclaim-off: "off"

migration-name: "_renamed" # Should there be a conflict with the trigger words, inside the DB the objects will be renamed to this name.

#Debugging
plugin-insights:
  enabled: true #Shows som additional debug information in the server console and when commands are executed.