name: VisualClaim
version: '0.3-SNAPSHOT'
main: dev.ewio.VisualClaim
api-version: '1.21'
author: Elias_Technik
softdepend:
  - Pl3xMap

commands:
  claim:
    description: Claim that chunk
    usage: /claim ["name"]
    permission: visualclaim.command.claim
  unclaim:
    description: Unclaim that chunk
    usage: /unclaim
    permission: visualclaim.command.unclaim
  deleteclaim:
    description: Delete a claim and unclaim all chunks in it
    usage: /deleteclaim "<name>"
    permission: visualclaim.command.deleteclaim
  autoclaim:
    description: Toggle autoclaim for a claim
    usage: /autoclaim <"name"|off>
    permission: visualclaim.command.autoclaim
  claiminfo:
    description: See who claimed that chunk you are standing on
    usage: /claiminfo
    permission: visualclaim.command.claiminfo
  listclaims:
    description: List all claims your claims
    usage: /listclaims
    permission: visualclaim.command.listclaims
  renameclaim:
    description: Rename a claim
    usage: /renameclaim "<oldname>" "<newname>"
    permission: visualclaim.command.renameclaim
  showclaim:
    description: Show the borders of a claim
    usage: /showclaim "<name>"
    permission: visualclaim.command.showclaim
  claimlore:
    description: Lets you read and set lore for a given claim
    usage: /claimlore "<name>" ["<lore>"]
    permission: visualclaim.command.claimlore
  claimcolor:
    description: Lets you set a color for your claim
    usage: /claimcolor "<name>" <color>
    permission: visualclaim.command.claimcolor
  chunkloader:
    description: Lets you load this chunk permanently
    usage: /chunkloader [add/remove]
    permissions: visualclaim.command.chunkloader



permissions:
  visualclaim.claim:
    description: "Allows claiming chunks"
    default: true
  visualclaim.maxclaims:
    description: "Overrides the max claims per player limit if a number or -1 is specified behind it"
    default: false
  visualclaim.maxchunks:
    description: "Overrides the max chunks per player limit if a number or -1 is specified behind it"
    default: false
  visualclaim.maxclaimlength:
    description: "Overrides the character limit of claim names for that player or -1 is specified behind it"
    default: false
  visualclaim.listother:
    description: "Allows listing other players' claims"
    default: false
  visualclaim.unclaimother:
    description:  "Allows unclaiming chunks from other players"
    default: false
  visualclaim.deleteother:
    description: "Allows deleting other players' claims"
    default: false
  visualclaim.renameother:
    description: "Allows renaming other players' claims"
    default: false