name: VisualClaim
version: '0.3-SNAPSHOT'
main: dev.ewio.VisualClaim
api-version: '1.21'
author: Elias_Technik
softdepend:
  - Pl3xMap

commands:
  claim:
    description: Claim that chunk
    usage: /claim ["name"]
    permission: visualclaim.claim
  unclaim:
    description: Unclaim that chunk
    usage: /unclaim
    permission: visualclaim.unclaim
  deleteclaim:
    description: Delete a claim and unclaim all chunks in it
    usage: /deleteclaim "<name>"
    permission: visualclaim.deleteclaim
  autoclaim:
    description: Toggle autoclaim for a claim
    usage: /autoclaim <"name"|off>
    permission: visualclaim.autoclaim
  claiminfo:
    description: See who claimed that chunk you are standing on
    usage: /claiminfo
    permission: visualclaim.claiminfo
  listclaims:
    description: List all claims your claims
    usage: /listclaims
    permission: visualclaim.listclaims
  renameclaim:
    description: Rename a claim
    usage: /renameclaim "<oldname>" "<newname>"
    permission: visualclaim.renameclaim
  showclaim:
    description: Show the borders of a claim
    usage: /showclaim "<name>"
    permission: visualclaim.showclaim
  claimlore:
    description: Lets you read and set lore for a given claim
    usage: /claimlore "<name>" ["<lore>"]
    permission: visualclaim.claimlore
  claimcolor:
    description: Lets you set a color for your claim
    usage: /claimcolor "<name>" <color>
    permission: visualclaim.claimcolor
  chunkloader:
    description: Lets you load this chunk permanently
    usage: /chunkloader [add/remove/list]
    permissions: visualclaim.chunkloader



permissions:
  visualclaim.claim:
    description: "Allows claiming chunks"
    default: false
  visualclaim.maxclaims:
    description: "Overrides the max claims per player limit if a number or -1 is specified behind it"
    default: false
  visualclaim.maxchunks:
    description: "Overrides the max chunks per player limit if a number or -1 is specified behind it"
    default: false
  visualclaim.maxclaimlength:
    description: "Overrides the character limit of claim names for that player or -1 is specified behind it"
    default: false
  visualclaim.listother:
    description: "Allows listing other players' claims"
    default: false
  visualclaim.unclaimother:
    description:  "Allows unclaiming chunks from other players"
    default: false
  visualclaim.deleteother:
    description: "Allows deleting other players' claims"
    default: false
  visualclaim.renameother:
    description: "Allows renaming other players' claims"
    default: false
  visualclaim.showother:
    description: "Allows showing other players' claim borders"
    default: false
  visualclaim.setloreother:
    description: "Allows setting lore for other players' claims"
    default: false
  visualclaim.setcolorother:
    description: "Allows setting colors for other players' claims"
    default: false
  visualclaim.loadChunks:
    description: "Allows using chunkloaders"
    default: false
